Added Front end and functionality
Cwagne17/Technical_Interview_2020 pull request #2
Opened 2020-10-30 16:39 UTC by Cwagne17

I implemented the front end.
Connected the back-end.

2020-10-30 16:54 UTC, pzalep1 requested changes
Good work on this! Just two small changes from me.

2020-10-30 16:54 UTC, pzalep1 commented on api/src/app.ts
> +  console.log(req.params.taskId);
:fire: console.log.

2020-10-30 16:54 UTC, pzalep1 commented on api/src/app.ts
> +    console.log(err);
This should just send the error. Usually there would be some processing of the error itself to give better context to the user, but for the purposes of this project just returning the error to the client would be sufficient.

2020-10-30 17:40 UTC, EVogel1999 commented on TakeHomeTest/src/app/web-request.service.ts
> +    this.ROOT_URL = "http://localhost:3000";
This is a really good method that we also use in both CARD and CLARK!  It's great for when we need to reference our deployed API versus our local development API.

2020-10-30 17:46 UTC, EVogel1999 approved these changes
Great work Chris!

2020-11-02 14:33 UTC, pzalep1 approved these changes
Good work on this!

2020-11-02 16:23 UTC, merged